image: node:8.11.1

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm install
    - npm run es6toes5-f7
    - npm run es6toes5-f7r
    - npm run es6toes5-dom7
    - npm run es6toes5-template7
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
