image: node:8.11.1

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  variables:
    REACT_APP_VERSION: $npm_package_version
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
